// <auto-generated />
using System;
using BookMart.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookMart.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookMart.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CoverImageURL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int?>("GenreID")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("int");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int?>("PublishedDate")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BookID");

                    b.HasIndex("GenreID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            Author = "Harper Lee",
                            CoverImageURL = "https://raw.githubusercontent.com/Sumeet-162/eCommerce.Net/refs/heads/main/images/to%20kill.jpg",
                            CreatedAt = new DateTime(2023, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A classic of modern American literature, 'To Kill a Mockingbird' by Harper Lee, published in 1960, explores themes of racial injustice and childhood innocence in the American South. The story is narrated by Scout Finch, a young girl whose lawyer father, Atticus Finch, defends a black man falsely accused of rape. This Pulitzer Prize-winning novel is celebrated for its powerful depiction of morality, prejudice, and courage.",
                            GenreID = 1,
                            ISBN = "9780061120084",
                            IsActive = true,
                            Language = "English",
                            MinStockLevel = 20,
                            PageCount = 336,
                            Price = 299.00m,
                            PublishedDate = 1960,
                            Publisher = "J. B. Lippincott & Co.",
                            StockQuantity = 50,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            BookID = 2,
                            Author = "Charles Duhigg",
                            CoverImageURL = "https://raw.githubusercontent.com/Sumeet-162/eCommerce.Net/refs/heads/main/images/the%20power.jpg",
                            CreatedAt = new DateTime(2023, 1, 2, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "In 'The Power of Habit: Why We Do What We Do in Life and Business,' Charles Duhigg, a Pulitzer Prize-winning reporter, explores the science behind habit formation and reformation. Published in 2012, the book delves into how habits function at individual, organizational, and societal levels, providing insights into how they can be changed for personal and business success.",
                            DiscountedPrice = 350.00m,
                            GenreID = 9,
                            ISBN = "9780812981605",
                            IsActive = true,
                            Language = "English",
                            MinStockLevel = 20,
                            PageCount = 400,
                            Price = 400.00m,
                            PublishedDate = 2012,
                            Publisher = "Random House",
                            StockQuantity = 75,
                            Title = "The Power of Habit"
                        },
                        new
                        {
                            BookID = 3,
                            Author = "F. Scott Fitzgerald",
                            CoverImageURL = "https://raw.githubusercontent.com/Sumeet-162/eCommerce.Net/refs/heads/main/images/the%20power.jpg",
                            CreatedAt = new DateTime(2023, 1, 3, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "A novel by F. Scott Fitzgerald, 'The Great Gatsby' is a classic of modern American literature, published in 1925. It details the decadent Jazz Age through the eyes of Nick Carraway, who recounts the enigmatic millionaire Jay Gatsby's opulent life and tragic pursuit of Daisy Buchanan. The novel explores themes of wealth, idealism, social upheaval, and the American Dream.",
                            GenreID = 1,
                            ISBN = "9780743273565",
                            IsActive = true,
                            Language = "English",
                            MinStockLevel = 20,
                            PageCount = 180,
                            Price = 350.00m,
                            PublishedDate = 1925,
                            Publisher = "Charles Scribner's Sons",
                            StockQuantity = 60,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            BookID = 4,
                            Author = "J.R.R. Tolkien",
                            CoverImageURL = "https://raw.githubusercontent.com/Sumeet-162/eCommerce.Net/refs/heads/main/images/the%20power.jpg",
                            CreatedAt = new DateTime(2023, 1, 4, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "J.R.R. Tolkien's 'The Hobbit,' published in 1937, is a fantastical journey following Bilbo Baggins, a hobbit who joins a quest with a group of dwarves to reclaim their treasure from the dragon Smaug. This beloved children's fantasy novel introduces readers to the rich world of Middle-earth, serving as a prequel to 'The Lord of the Rings' and filled with adventures, riddles, and magical creatures.",
                            GenreID = 3,
                            ISBN = "9780547928227",
                            IsActive = true,
                            Language = "English",
                            MinStockLevel = 20,
                            PageCount = 310,
                            Price = 450.00m,
                            PublishedDate = 1937,
                            Publisher = "George Allen & Unwin",
                            StockQuantity = 80,
                            Title = "The Hobbit"
                        });
                });

            modelBuilder.Entity("BookMart.Models.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreID"));

                    b.Property<string>("ColorTheme")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GenreID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreID = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fiction"
                        },
                        new
                        {
                            GenreID = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Science Fiction"
                        },
                        new
                        {
                            GenreID = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantasy"
                        },
                        new
                        {
                            GenreID = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mystery"
                        },
                        new
                        {
                            GenreID = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Thriller"
                        },
                        new
                        {
                            GenreID = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Romance"
                        },
                        new
                        {
                            GenreID = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Biography"
                        },
                        new
                        {
                            GenreID = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "History"
                        },
                        new
                        {
                            GenreID = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Self-Help"
                        },
                        new
                        {
                            GenreID = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cookbook"
                        });
                });

            modelBuilder.Entity("BookMart.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BookMart.Models.Book", b =>
                {
                    b.HasOne("BookMart.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreID");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BookMart.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
